config/routes.rb
Rails.application.routes.draw do
  get 'readmissions/new'
  get 'readmissions/create'
  get 'readmissions/index'
  get 'document_requests/new'
  get 'document_requests/create'
  get 'document_requests/show'
  get 'reports/course_assignments'
  get 'grade_changes/new'
  get 'grade_changes/create'

  resources :sections, except: [:index] do
    collection do
      get "assign", to: "sections#index"
    end
    member do
      get :download_pdf
    end
  end
  
  resources :attendances do
    member do
      get :download_pdf
    end
  end

  resources :academic_calendars do
    member do
      get :download_pdf
    end
  end

  resources :notices, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  #resources :makeup_exams, only: [:new, :create]
  resources :withdrawals, only: [:new, :create]

  get 'course_assignments', to: 'reports#course_assignments', as: 'course_assignments_report'
  
  #resources :makeup_exams do
  #  member do
  #    patch :verify
  #  end
  #end
  #get 'courses/pdf/:scope', to: 'courses#pdf_by_scope', as: 'courses_pdf_by_scope'
 # post 'admin/class_schedules/:id/upload_file', to: 'admin/class_schedules#upload_file', as: 'upload_file_admin_class_schedule'

  
  resources :makeup_exams, only: [:index, :new, :create] do
    member do
      get :payment
      patch :payment, action: :update
      patch :verify
    end
  end
  
  #resources :payments, only: [:new, :create] do
  #  member do
  #    get :pay
  #  end
  #end

 # resources :sections do
 #   member do
 #     get :download_pdf
 #   end
 # end
#
 # resources :sections, except: [:index] do
 #   collection do
 #     get "assign", to: "sections#index"
 #     # as: "sections" 
 #   end
 # end
  get 'apply_grade_change/index'
  get '/available/courses/:course_id/(:drop_id)', to: "avaliable_courses#index", as: "available_courses"
  get 'drop_courses/index', as: 'drop_courses'
  get 'add_courses/index', as: "add_courses"
  post "create/exemptions/:applicant_id", to: 'exemptions#create', as: 'create_exemptions'
  get "new/exemptions/:applicant_id/:approved_by", to: 'exemptions#new', as: 'new_exemptions'
  get "index/exemptions/:applicant_id/:approved_by", to: 'exemptions#index', as: 'index_exemptions'
  get "edit/exemptions/:applicant_id/:id/:approved_by", to: 'exemptions#edit', as: 'edit_exemptions'
  get "applicant/search", to: "external_transfers#search", as: 'external_transfer_search'
  get "transfer/approval/:id/:approved_by", to: "external_transfers#approval", as: "transfer_approval"
  patch "transfer/approved/:id", to: "external_transfers#approved", as: "transfer_approved"
  delete "delete/exception", to: "exemptions#destroy", as: "transfer_destroy"
  resources :avaliable_courses, except: [:index]
  resources :drop_courses do
    member do
      post "add_course_drop", as: "add_drop_course"
      post "withdraw_course"
    end
  end
  # config/routes.rb
resources :courses do
  resources :assessment_plans, only: [:index, :new, :create, :edit, :update, :destroy]
end
resources :courses, only: [:index, :show]

resources :assessment_plans do
  resources :assessments do
    resources :assessment_results, only: [:create]
  end
end


resources :document_requests, only: [:index, :new, :create, :show] do

  member do
    get :payment
    patch :upload_receipt
  end

  collection do
    get :track_form
    post :track
  end

end
# config/routes.rb
#resources :assessmens do
#  collection do
#    get :missing_assessments_report
#  end
#end


  resources :exemptions

 # resources :exemptions do
 #   collection do
 #     get :courses_for_transfer
 #     #post :select_course
 #   end
 # end

  #resources :external_transfers

  resources :external_transfers do
    
    collection do
      get :filter_programs
    end

    member do
      get :payment
      patch :payment
    end

  end


  resources :transfers, only: [:new, :create] do
    member do
      patch :process_course_exemption
    end
  end
  
  resources :program_exemptions, only: [:new, :create]
  
  resources :assessmens do
    collection do
      post :bulk_create
      get :find_course
      get :missing_assessments_report
    end
    member do
      put :update_mark
      put :batch_update
    end
  end
  
  namespace :admin do
    resources :registration_payments do
      member do
        get :download_pdf
      end
    end
  end

  
namespace :admin do
  resources :class_schedules do
    collection do
      get :fetch_courses_and_sections
    end
  end
end

resources :course_offerings
resources :class_schedules, only: [:index]
  #resources :class_schedules, only: [:index]
  resources :exam_schedules, only: [:index, :new, :create, :edit, :update]

  resources :readmissions, only: [:index, :new, :create] do
    member do
      get :payment
      patch :payment, action: :update
      patch :verify
    end
  end

  get "student_temporary/index", as: "student_temporary"
  post "student/tempo/generate", to: "student_temporary#generate_pdf", as: "generate_student_tempo"
  get "pdf_grade_reports/index", as: "pdf_gread_report"
  get "prepare_pdf.pdf", to: "pdf_grade_reports#prepare_pdf"
  get "student/tempo/generate.pdf", to: "student_temporary#generate_pdf"
  get "graduation/approval", to: "student_temporary#graduation_approval", as: "graduation_approval"
  get "graduation/approval/form", to: "student_temporary#graduation_approval_form", as: "graduation_approval_form"
  get "approved", to: "student_temporary#approved", as: "approved"
  get "student/generate/copy", to: "student_copy#index", as: "student_copy"
  post "student_copy/generate_student_copy", as: "generate_student_copy"
  get "new/semester/registration", to: "pages#enrollement", as: "enrollement"
  get "added/course/registration", to: "pages#add_enrollement", as: "add_enrollement"

  # post "added/course/registration", to: "pages#added_course_registration", as: "added_course_registration"
  post "create/semester/registration/(:out_of_batch)", to: "pages#create_semester_registration", as: "create_semester_registration"
  
  get "student/grade/report/:year/:semester", to: "grade_reports#student_grade_report", as: "student_grade_report"
  get "prepare/payment/:semester_registration_id", to: "invoices#prepare_payment", as: "prepare_payment"
  post "create/invoice", to: "invoices#create_invoice_for_remaining_amount", as: "create_invoice_for_remaining_amount"
  get "payment/report/fetch/student", to: "payment_report#fetch_student", as: "payment_report_fetch_student"
  get "get/year", to: "payment_report#get_year", as: "payment_report_get_year"
  get "get/semester", to: "payment_report#get_semester", as: "payment_report_get_semester"
  get "student/report", to: "student_report#get_student_list", as: "student_report"
  get "/student/report/year", to: "student_report#student_report_year", as: "student_report_year"
  get "/student/report/program", to: "student_report#student_report_program", as: "student_report_program"
  get "/student/gc/program", to: "student_report#student_report_gc", as: "student_report_gc"
  get "/student/report/gc/year", to: "student_report#student_report_gc_year", as: "student_report_gc_year"
  get "/student/report/semester", to: "student_report#student_report_semester", as: "student_report_semester"
  get "/prepare/online/student/grade", to: "online_student_grade#prepare", as: "online_student_grade_prepare"
  post "/student/pdf/report.pdf", to: "student_report#student_report_pdf", as: "student_report_pdf"
  post "generate/payment/report.pdf", to: "payment_report#generate_payment_report", as: "generate_payment_report"
  get "/online/student/grade", to: "online_student_grade#online_grade", as: "online_grade"
  post "/approve/online/student/grade", to: "online_student_grade#approve_grade", as: "approve_online_grade"
  resources :grade_reports
  resources :academic_calendars, only: [:show, :index]
  devise_for :students, controllers: {
                          registrations: "registrations",
                        }
  authenticated :student do
    root "pages#dashboard", as: "authenticated_user_root"
  end
  devise_scope :student do
    put "update/highschool/transcript", to: "registrations#update_highschool_transcript", as: "update_highschool_transcript"
    put "update/grade/10/matric", to: "registrations#update_grade_10_matric", as: "update_grade_10_matric"
    put "update/grade/12/matric", to: "registrations#update_grade_12_matric", as: "update_grade_12_matric"
    put "update/coc", to: "registrations#update_coc", as: "update_coc"
    put "update/profile/photo", to: "registrations#update_profile_photo", as: "update_profile_photo"
    put "update/diploma/certificate", to: "registrations#update_diploma_certificate", as: "update_diploma_certificate"
    put "update/degree/certificate", to: "registrations#update_degree_certificate", as: "update_degree_certificate"
  end

  namespace :admin do
    resources :sections do
      member do
        get :download_pdf
      end
    end
  end

  resources :semester_registrations do
    member do
      get :download_pdf
    end
  end
  
  
  post "prepare_pdf", to: "pdf_grade_reports#prepare_pdf", as: "prepare_pdf"
  get "admission" => "pages#admission"
  get "documents" => "pages#documents", as: "documents"
  get "profile" => "pages#profile", as: "profile"
  get "grade_report" => "pages#grade_report"
  get "digital-iteracy-quiz" => "pages#digital_iteracy_quiz"
  get "requirements" => "pages#requirement"
  get "home" => "pages#home"
  resources :almunis
  resources :semester_registrations
  resources :invoices
  resources :profiles
  resources :grade_changes, only: [:new, :create]
  resources :payment_methods
  resources :payment_transactions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: 'application#home'

end

app/controllers/semester_registrations_controller.rb
class SemesterRegistrationsController < ApplicationController
  before_action :set_registration, only: %i[ show edit update destroy ]

  # GET /registrations or /registrations.json
  def index
    @semester_registrations = current_student.semester_registrations.all
  end

  # GET /registrations/1 or /registrations/1.json
  def show
  end

  # GET /registrations/new
  def new
    @semester_registration = SemesterRegistration.new
  end

  # GET /registrations/1/edit
  def edit
    # @course_registrations = semester_registration.course_registrations.where(year: current_student.year, semester: current_student.semester)

   
    #@registration_fee = CollegePayment.where(study_level: @semester_registration.study_level,admission_type: @semester_registration.admission_type).first.registration_fee 
    
    #if current_student.year == 1 && current_student.semester == 1
     # @tution_fee = (@semester_registration.course_registrations.collect { |oi| oi.valid? ? (CollegePayment.where(study_level: @semester_registration.study_level,admission_type: @semester_registration.admission_type).first.tution_per_credit_hr * oi.course.credit_hour) : 0 }.sum) + 2100
    
   # else 
    #  @tution_fee = (@semester_registration.course_registrations.collect { |oi| oi.valid? ? (CollegePayment.where(study_level: @semester_registration.study_level,admission_type: @semester_registration.admission_type).first.tution_per_credit_hr * oi.course.credit_hour) : 0 }.sum)
    #end
    
   # @total = @registration_fee + @tution_fee


    @registration_fee = current_student.get_registration_fee
    @tution_fee =  current_student.get_tuition_fee

  end

  # POST /registrations or /registrations.json
  def create
    @semester_registration = SemesterRegistration.new(semester_registration_params)

    respond_to do |format|
      if @semester_registration.save
        format.html { redirect_to @semester_registration, notice: "semester_registration was successfully created." }
        format.json { render :show, status: :created, location: @semester_registration }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @semester_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registrations/1 or /registrations/1.json
  def update
    respond_to do |format|
      if @semester_registration.update(semester_registration_params)
        format.html { redirect_to invoice_path(@semester_registration.invoices.last.id), notice: "Registration was successfully updated." }
        format.json { render :show, status: :ok, location: @semester_registration }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @semester_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrations/1 or /registrations/1.json
  def destroy
    @semester_registration.destroy
    respond_to do |format|
      format.html { redirect_to semester_registrations_url, notice: "semester_registration was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def download_pdf
    @semester_registration = SemesterRegistration.find(params[:id])
                                                      
    pdf = Prawn::Document.new
  
    # Add the logo at the top center
    logo_path = Rails.root.join('app/assets/images/logo.jpg')
    pdf.image logo_path, at: [pdf.bounds.width / 2 - 50, pdf.cursor], width: 100
    pdf.move_down 60
  
    pdf.text "Student Registration Information", size: 20, style: :bold, align: :center
    pdf.move_down 20
    pdf.text "Full Name: #{@semester_registration.student_full_name}"
    pdf.text "Student ID: #{@semester_registration.student_id_number}"
    pdf.text "Program: #{@semester_registration.program.program_name}"
    pdf.text "Department: #{@semester_registration.department.department_name}" if @semester_registration.department.present?
    pdf.text "Year: #{@semester_registration.year}"
    pdf.text "Semester: #{@semester_registration.semester}"
    pdf.move_down 20
  
    pdf.text "Course Registrations", size: 18, style: :bold
    pdf.move_down 10
  
    table_data = [["No", "Course Name", "Code", "Credit Hour", "Contact Hour"]]
  
    total_credit_hours = 0
    total_contact_hours = 0
  
    @semester_registration.course_registrations.each_with_index do |registration, index|
      table_data << [
        index + 1,
        registration.course.course_title,
        registration.course.course_code,
        registration.course.credit_hour,
        registration.course.ects
      ]
      total_credit_hours += registration.course.credit_hour
      total_contact_hours += registration.course.ects
    end
  
    pdf.table(table_data, header: true, row_colors: ["F0F0F0", "FFFFFF"], cell_style: { borders: [:top, :bottom] }) do
      row(0).font_style = :bold
      row(0).background_color = "CCCCCC"
    end
  
    pdf.move_down 20
    pdf.text "Total Credit Hours: #{total_credit_hours}", size: 14, style: :bold
    pdf.text "Total Contact Hours: #{total_contact_hours}", size: 14, style: :bold
  
    send_data pdf.render, filename: "semester_registration_#{@semester_registration.id}.pdf", type: 'application/pdf'
   
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration
      @semester_registration = SemesterRegistration.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def semester_registration_params
      params.fetch(:semester_registration, {}).permit(:mode_of_payment)
    end
end

app/views/semester_registrations/_form.html.erb
<%= simple_form_for(@semester_registration) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="col-12 col-md-12 form-group">
    <%= f.input :mode_of_payment, as: :select, :collection =>  [ "Monthly Payment", "Full Semester Payment"], input_html: {class: "form-control custom-select"}, :include_blank => false%>
  </div>

  <div class="form-actions">
    <%= f.submit "Finish", class: "btn btn-primary btn-user" %>
  </div>
<% end %>

app/views/semester_registrations/edit.html.erb
<%provide(:title, "Student Registrations")%>
<link type="text/css" href="//gyrocode.github.io/jquery-datatables-checkboxes/1.2.12/css/dataTables.checkboxes.css" rel="stylesheet" />
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Semester Registration</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active">Semester Registration</li>
        </ol>
      </div>
    </div>
  </div>
  <!-- /.container-fluid -->
</section>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-md-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Registration Form</h3>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-12 col-md-6">
                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item mx-3">
                    <b>Student Fullname</b> <a class="text-muted float-right"><%= current_student.name.full.upcase%></a>
                  </li>
                  <li class="list-group-item mx-3">
                    <b>Student ID</b> <a class="text-muted float-right"><%= current_student.student_id.present? ? current_student.student_id : "Not Assigned Yet"%></a>
                  </li>
                  <li class="list-group-item mx-3">
                    <b>Prorgam</b> <a class="text-muted float-right"><%= current_student.program.program_name%></a>
                  </li>
                  <li class="list-group-item mx-3">
                    <b>Admission Type</b> <a class="text-muted float-right"><%= current_student.admission_type%></a>
                  </li>
                </ul>
              </div>
              <div class="col-12 col-md-6">
                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item mx-3">
                    <b>Academic Year</b> <a class="text-muted float-right"><%= current_student.academic_calendar.calender_year%></a>
                  </li>
                  <li class="list-group-item mx-3">
                    <b>Study Level</b> <a class="text-muted float-right"><%= current_student.study_level%></a>
                  </li>
                  <li class="list-group-item mx-3">
                    <b>Year</b> <a class="text-muted float-right"><%= current_student.year%></a>
                  </li>
                  <li class="list-group-item mx-3">
                    <b>Semester</b> <a class="text-muted float-right"><%= current_student.semester%></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Program Courses</h3>
          </div>
          <div class="card-body">
            <table id='ordersTable' class='table table-striped table-sm'>
              <thead>
                <tr>
                  <th>Course Title</th>
                  <th>Module Code</th>
                  <th>Course Code</th>
                  <th>Credit Hour</th>
                </tr>
              </thead>
              <tbody>
                <% current_student.program.curriculums.where(active_status: "active").first.courses.where(year: current_student.year, semester: current_student.semester).order('year ASC
','semester ASC').each do |course_registration| %>
                  <tr>
                    <td><%= course_registration.course_title %></td>
                    <td><%= course_registration.course_module.module_code %></td>
                    <td><%= course_registration.course_code %></td>
                    <td><%= course_registration.credit_hour %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="col-12">
        <!-- <p class="lead">Amount Due 2/22/2014</p> -->
        
        <div class="row">
          <% if @tution_fee.nil? || @registration_fee.nil?%>
            <div class="m-3">
              <h2 class="card-title text-danger">Program payment is not set yet, please contact finance head </h2>
            </div>
          <%else%>
            <div class="col-12 col-md-4">
              <div class="card card-primary shadow">
                <div class="card-header">
                  <h3 class="card-title">Monthly Pricing Option</h3>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <tbody>
                        <tr>
                          <th style="width:50%">Monthly Subtotal:</th>
                          <td><%= sub_total(@tution_fee, 3).round(2) %> ETB</td>
                        </tr>
                        <tr>
                          <th>Registration Fee:</th>
                        <!--  <td><%= (@registration_fee / 4) %> ETB</td> -->
                          <td><%= (@registration_fee) %> ETB</td>
                        </tr>
                        <tr>
                          <th>Total:</th>
                         <!-- <td><b><%= total(@tution_fee, 4 , @registration_fee / 4) %> ETB</b></td> -->
                          <td><b><%= total(@tution_fee, 3 , @registration_fee).round(2) %> ETB</b></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

            

            <div class="col-12 col-md-4">
              <div class="card card-warning shadow">
                <div class="card-header">
                  <h3 class="card-title">Full Semester payment Mode</h3>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <tbody>
                        <tr>
                          <th style="width:50%">Full Subtotal Payment:</th>
                          <td><%= sub_total(@tution_fee, 1) %> ETB</td>
                        </tr>
                        <tr>
                          <th>Registration Fee:</th>
                          <td><%= @registration_fee %> ETB</td>
                        </tr>
                        <tr>
                          <th>Total:</th>
                          <td><b><%= total(@tution_fee, 1 , @registration_fee) %> ETB</b></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12 col-md-12">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Select payment Mode</h3>
            </div>
            <div class="card-body">
              <%= render 'form', semester_registration: @semester_registration %>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</section>
<script type="text/javascript" src="//gyrocode.github.io/jquery-datatables-checkboxes/1.2.12/js/dataTables.checkboxes.min.js"></script>
<!-- 
<script>
  $(document).ready(function() {
    var oTable = $("#ordersTable").DataTable({
      order: [[2, 'desc']],
      columnDefs: [
        {
          targets: 0,
          checkboxes: {
            selectRow: true
          }
        }
      ],
      select: {
        style: 'multi'
      }
    });

  // 		$('#selectAll').on('click', function(params) {
		// 	var rows_selected = oTable.column(0).checkboxes.selected();
			
		// 	if (rows_selected.length == oTable.page.len()) {
		// 		oTable.column(0).checkboxes.select(false);
		// 	} else {
		// 		oTable.column(0).checkboxes.select(true);
		// 	}
		// })

 	// 	$('.bulkActionLink').on('click', function(params) {
		// 	// console.log(this.dataset.action)
		// 	var rows_selected = oTable.column(0).checkboxes.selected();

		// 	if (rows_selected.length > 0) {
		// 		$("#formActionType").val(this.dataset.action);
		// 		$("#bulkActionsForm").submit();
		// 	}
		// })

	// do something with all selected rows
		// $('#bulkActionsForm').on('submit', function(e){
		// 	var form = this;

		// 	var rows_selected = oTable.column(0).checkboxes.selected();

		// 	// Iterate over all selected checkboxes
		// 	$.each(rows_selected, function(index, rowId){
		// 		// Create a hidden element
		// 		$(form).append(
		// 			$('<input>')
		// 			.attr('type', 'hidden')
		// 			.attr('name', 'id[]')
		// 			.val(rowId)
		// 		);
		// 	});
		// });


  });
</script> -->

app/views/semester_registrations/index.html.erb
<%provide(:title, "semester_registration")%>

<section class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1>My Semester Registration</h1>
			</div>
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="/">Home</a></li>
					<li class="breadcrumb-item active">semester registration</li>
				</ol>
			</div>
		</div>
	</div><!-- /.container-fluid -->
</section>

<div class="col-12 col-md-12">
	<div class="card card-primary">
		<div class="card-header">
			<h3 class="card-title">semester registration History</h3>
		</div>
		<div class="card-body">
			<table id='ordersTable' class='table table-striped table-sm'>
				<thead>
					<tr>
						<th>Student Name</th>
						<th>Student ID</th>
						<th>Academic Year</th>
						<th>Semester</th>
						<th>Year</th>
						<th>Registration Date</th>
						
						<th>Actions</th>
					</tr>
				</thead>

				<tbody>
					<%@semester_registrations.each do |sm|%>
							<tr>
								<td><%= sm.student.name.full  %></td>
								<td><%= sm.student.student_id %></td>
								<td><%= sm.academic_calendar.calender_year %></td>
								<td><%= sm.semester %></td>
								<td><%= sm.year %></td>
								<td><%= sm.created_at.strftime("%b %d, %Y") %></td>
								
								<td class="actions">
  									<%= link_to("View", semester_registration_path(sm), class: 'btn-sm btn-primary') %>
 								    <%= link_to("Download", download_pdf_semester_registration_path(sm), class: 'btn-sm btn-success') %>
								</td>

							</tr>
					<%end%>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/semester_registrations/new.html.erb
<%provide(:title, "Student Registrations")%>

<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Semester Registration</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active">Semester Registration</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-md-12">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Select payment Mode</h3>
          </div>
          <div class="card-body">
          	<%= render 'form', semester_registration: @semester_registration %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<%= link_to 'Back', semester_registrations_path %>